defaults:
  - game: basic
  - explore_space: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  
  
seed: 42

# experiment outputs: uses hydra.job.chdir to unique
filepaths: 
  curve_points_save_fn: curve_points.csv
  simulation_points_save_fn: simulation_points.csv
  sampled_points_save_fn: sampled_points.csv
  tradeoff_plot_fn: tradeoff.txt

# for hydra folder naming
# subdir: /size=${game.size}/similarity=${game.similarity}/distortion=${distortion}/dynamics=${simulation.dynamics}/num_trials=${simulation.num_trials}/seed=${seed}

hydra:
  run:
    dir: outputs/size=${game.size}/similarity=${game.similarity}/distortion=${game.distortion}/dynamics=${simulation.dynamics}/num_trials=${simulation.num_trials}/seed=${seed}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - game.size
          - game.similarity
          - game.distortion
          - simulation.dynamics
          - simulation.num_trials
          - seed
  sweep:
    dir: multirun
    subdir: size=${game.size}/similarity=${game.similarity}/distortion=${game.distortion}/dynamics=${simulation.dynamics}/num_trials=${simulation.num_trials}/seed=${seed}
  
# for sweeping params
# python rdsg.py -m game.similarity.param=range(1,5)