defaults:
  - game: basic
  - explore_space: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  
  
seed: 42

filepaths: 
  # experiment outputs
  curve_points_save_fn: curve_points.csv
  simulation_points_save_fn: simulation_points.csv
  sampled_points_save_fn: sampled_points.csv
  counterpart_points_fn: counterpart_points.csv
  tradeoff_plot_fn: tradeoff.png
  # hydra automatic folder naming
  game_subdir: states=${game.size.num_states}/signals=${game.size.num_signals}/similarity=${game.similarity.func}/distortion=${game.distortion}
  simulation_subdir: dynamics=${simulation.dynamics.name}/num_trials=${simulation.num_trials}/sim_param=${game.similarity.param}
  leaf_subdir: ${filepaths.game_subdir}/${filepaths.simulation_subdir}

hydra:
  run:
    dir: outputs/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - game.size.num_states
          - game.size.num_signals
          - game.similarity.func
          - game.similarity.param          
          - game.distortion
          - simulation.dynamics.name
          - simulation.num_trials
  sweep:
    dir: multirun
    subdir: ${filepaths.leaf_subdir}
  
# example command for sweeping params
# python rdsg.py -m game.similarity.param=range(1,10, 2)