hydra:
  run:
    dir: outputs/${filepaths.leaf_subdir}
  sweep:
    dir: multirun
    subdir: ${filepaths.leaf_subdir}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - game/similarity=nosofsky_normed
    - game.distortion=squared_dist
    - simulation.num_trials=100
    - explore_space/pool_size=large
    - game.similarity.param=0, 1, 2, 4, 6, 8, 16
    - simulation/dynamics=replicator_dynamic
  job:
    name: run_simulations
    chdir: true
    override_dirname: explore_space/pool_size=large,game/similarity=nosofsky_normed,simulation/dynamics=replicator_dynamic
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - filepaths.leaf_subdir
        - game.size.num_states
        - game.size.num_signals
        - game.similarity.func
        - game.similarity.param
        - game.distortion
        - simulation.dynamics.name
        - simulation.num_trials
        - simulation.dynamics.rate
  runtime:
    version: 1.3.1
    version_base: '1.3'
    cwd: /Users/nathanielimel/lps/projects/rdsg
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/nathanielimel/lps/projects/rdsg/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      simulation: basic
      simulation/dynamics: replicator_dynamic
      explore_space: basic
      explore_space/pool_size: large
      explore_space/directions: all
      game: basic
      game/size: ten
      game/similarity: nosofsky_normed
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
game:
  similarity:
    func: nosofsky_normed
    param: 0
  size:
    num_states: 10
    num_signals: 10
  distortion: squared_dist
explore_space:
  directions:
    lower_left: true
    lower_right: true
    upper_left: true
    upper right: true
  pool_size:
    seed_generation_size: 1000.0
    max_mutations: 5
    num_generations: 200
simulation:
  dynamics:
    name: replicator_dynamic
    max_its: 200
    threshold: 1.0e-05
    speed: 1.0
  num_trials: 100
  trajectory: false
seed: 42
multiprocessing: true
num_processes: null
filepaths:
  curve_points_save_fn: curve_points.csv
  simulation_points_save_fn: simulation_points.csv
  sampled_points_save_fn: sampled_points.csv
  mean_points_save_fn: mean_points.csv
  counterpart_points_fn: counterpart_points.csv
  tradeoff_plot_fn: tradeoff.png
  game_subdir: states=${game.size.num_states}/signals=${game.size.num_signals}/distortion=${game.distortion}
  simulation_subdir: similarity=${game.similarity.func}/dynamics=${simulation.dynamics.name}/num_trials=${simulation.num_trials}/sim_param=${game.similarity.param}
  leaf_subdir: ${filepaths.game_subdir}/${filepaths.simulation_subdir}
