hydra:
  run:
    dir: outputs/size=${game.size}/similarity=${game.similarity}/distortion=${game.distortion}/dynamics=${simulation.dynamics}/num_trials=${simulation.num_trials}/seed=${seed}
  sweep:
    dir: multirun
    subdir: size=${game.size}/similarity=${game.similarity}/distortion=${game.distortion}/dynamics=${simulation.dynamics}/num_trials=${simulation.num_trials}/seed=${seed}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - game.similarity.param=range(1,5)
    - seed=1
    - game.similarity.func=exp
  job:
    name: rdsg
    chdir: true
    override_dirname: game.similarity.func=exp,game.similarity.param=range(1,5)
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - game.size
        - game.similarity
        - game.distortion
        - simulation.dynamics
        - simulation.num_trials
        - seed
  runtime:
    version: 1.3.1
    version_base: '1.3'
    cwd: /Users/nathanielimel/lps/projects/rdsg
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/nathanielimel/lps/projects/rdsg/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      simulation: basic
      simulation/dynamics: reinforcement-learning
      explore_space: basic
      explore_space/pool_size: medium
      explore_space/directions: all
      game: basic
      game/size: ten
      game/similarity: nosofsky
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
game:
  similarity:
    func: exp
    param: ???
  size:
    num_states: 10
    num_signals: 10
  distortion: squared_dist
explore_space:
  directions:
    lower_left: true
    lower_right: true
    upper_left: true
    upper right: true
  pool_size:
    seed_generation_size: 1000.0
    max_mutations: 3
    generations: 100
simulation:
  dynamics:
    reinforcement_learning:
      num_rounds: 100000.0
      learning_rate: 1.0
  num_trials: 1
seed: 1
filepaths:
  curve_points_save_fn: curve_points.csv
  simulation_points_save_fn: simulation_points.csv
  sampled_points_save_fn: sampled_points.csv
  tradeoff_plot_fn: tradeoff.txt
